python train_diffusion.py --tasks close_door \
    --dataset /home/zhouxian/git/datasets/packaged/diffusion_trajectories_train/ \
    --valset /home/zhouxian/git/datasets/packaged/diffusion_trajectories_va/ \
    --instructions instructions_new.pkl \
    --checkpoint /home/zhouxian/git/hiveformer/train_logs/diffuse_05_23/close_door_version0/model.step=105000-value=0.00000.pth \
    --use_instruction 0 \
    --use_goal 1 \
    --val_freq 1 \
    --checkpoint_freq 2 \
    --exp_log_dir debug \
    --run_log_dir close_door \
    --batch_size 24 --batch_size_val 12 --lr 1e-4
